const express = require("express");
const app = express();
const port = 3000;
const mongoose = require("mongoose");
mongoose.connect("mongodb://localhost:27017/saraha");
app.use(express.json());
app.use("/", require("./apis/user.api"));
app.use("/", require("./apis/message.api.js"));
app.get("/", (req, res) => res.send("Hello World!"));
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
